package core

func MakeConfig() map[string]any {
	return map[string]any{
		"main": map[string]any{
			"name": "Openverse",
		},
		"feature": map[string]any{
			"test": map[string]any{
				"options": map[string]any{
					"active": false,
				},
			},
		},
		"options": map[string]any{
			"base": "https://api.openverse.org",
			"auth": map[string]any{
				"prefix": "Bearer",
			},
			"headers": map[string]any{
				"content-type": "application/json",
			},
			"entity": map[string]any{
				"audio": map[string]any{},
				"image": map[string]any{},
				"o_auth2_application": map[string]any{},
				"o_auth2_key_info": map[string]any{},
				"o_auth2_token": map[string]any{},
			},
		},
		"entity": map[string]any{
			"audio": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "alt_file",
						"req": true,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "attribution",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "audio_set",
						"req": true,
						"type": "`$ANY`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "bit_rate",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 3,
					},
					map[string]any{
						"name": "category",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 4,
					},
					map[string]any{
						"name": "creator",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 5,
					},
					map[string]any{
						"name": "creator_url",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 6,
					},
					map[string]any{
						"name": "description",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 7,
					},
					map[string]any{
						"name": "detail_url",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 8,
					},
					map[string]any{
						"name": "display_name",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 9,
					},
					map[string]any{
						"name": "duration",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 10,
					},
					map[string]any{
						"name": "fields_matched",
						"req": true,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 11,
					},
					map[string]any{
						"name": "filesize",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 12,
					},
					map[string]any{
						"name": "filetype",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 13,
					},
					map[string]any{
						"name": "foreign_landing_url",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 14,
					},
					map[string]any{
						"name": "genre",
						"req": false,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 15,
					},
					map[string]any{
						"name": "id",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 16,
					},
					map[string]any{
						"name": "identifier",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 17,
					},
					map[string]any{
						"name": "indexed_on",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 18,
					},
					map[string]any{
						"name": "len",
						"req": true,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 19,
					},
					map[string]any{
						"name": "license",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 20,
					},
					map[string]any{
						"name": "license_url",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 21,
					},
					map[string]any{
						"name": "license_version",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 22,
					},
					map[string]any{
						"name": "logo_url",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 23,
					},
					map[string]any{
						"name": "mature",
						"req": true,
						"type": "`$BOOLEAN`",
						"active": true,
						"index$": 24,
					},
					map[string]any{
						"name": "media_count",
						"req": true,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 25,
					},
					map[string]any{
						"name": "point",
						"req": true,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 26,
					},
					map[string]any{
						"name": "provider",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 27,
					},
					map[string]any{
						"name": "reason",
						"req": true,
						"type": "`$ANY`",
						"active": true,
						"index$": 28,
					},
					map[string]any{
						"name": "related_url",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 29,
					},
					map[string]any{
						"name": "sample_rate",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 30,
					},
					map[string]any{
						"name": "source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 31,
					},
					map[string]any{
						"name": "source_name",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 32,
					},
					map[string]any{
						"name": "source_url",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 33,
					},
					map[string]any{
						"name": "tag",
						"req": true,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 34,
					},
					map[string]any{
						"name": "thumbnail",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 35,
					},
					map[string]any{
						"name": "title",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 36,
					},
					map[string]any{
						"name": "url",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 37,
					},
					map[string]any{
						"name": "waveform",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 38,
					},
				},
				"name": "audio",
				"op": map[string]any{
					"create": map[string]any{
						"name": "create",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"kind": "param",
											"name": "identifier",
											"orig": "identifier",
											"reqd": true,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "POST",
								"orig": "/v1/audio/{identifier}/report/",
								"parts": []any{
									"v1",
									"audio",
									"{identifier}",
									"report",
								},
								"select": map[string]any{
									"$action": "report",
									"exist": []any{
										"identifier",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "create",
					},
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"kind": "query",
											"name": "category",
											"orig": "category",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "creator",
											"orig": "creator",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "excluded_source",
											"orig": "excluded_source",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "extension",
											"orig": "extension",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": true,
											"kind": "query",
											"name": "filter_dead",
											"orig": "filter_dead",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "length",
											"orig": "length",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "license",
											"orig": "license",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "license_type",
											"orig": "license_type",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "mature",
											"orig": "mature",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": 1,
											"kind": "query",
											"name": "page",
											"orig": "page",
											"reqd": false,
											"type": "`$INTEGER`",
											"active": true,
										},
										map[string]any{
											"example": 20,
											"kind": "query",
											"name": "page_size",
											"orig": "page_size",
											"reqd": false,
											"type": "`$INTEGER`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "peak",
											"orig": "peak",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "q",
											"orig": "q",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "source",
											"orig": "source",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "tag",
											"orig": "tag",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "title",
											"orig": "title",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "unstable_authority",
											"orig": "unstable_authority",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": 1,
											"kind": "query",
											"name": "unstable_authority_boost",
											"orig": "unstable_authority_boost",
											"reqd": false,
											"type": "`$NUMBER`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "unstable_collection",
											"orig": "unstable_collection",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "unstable_include_sensitive_result",
											"orig": "unstable_include_sensitive_result",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": "relevance",
											"kind": "query",
											"name": "unstable_sort_by",
											"orig": "unstable_sort_by",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "desc",
											"kind": "query",
											"name": "unstable_sort_dir",
											"orig": "unstable_sort_dir",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "unstable_tag",
											"orig": "unstable_tag",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/v1/audio/",
								"parts": []any{
									"v1",
									"audio",
								},
								"select": map[string]any{
									"exist": []any{
										"category",
										"creator",
										"excluded_source",
										"extension",
										"filter_dead",
										"length",
										"license",
										"license_type",
										"mature",
										"page",
										"page_size",
										"peak",
										"q",
										"source",
										"tag",
										"title",
										"unstable_authority",
										"unstable_authority_boost",
										"unstable_collection",
										"unstable_include_sensitive_result",
										"unstable_sort_by",
										"unstable_sort_dir",
										"unstable_tag",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
							map[string]any{
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"kind": "param",
											"name": "identifier",
											"orig": "identifier",
											"reqd": true,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/v1/audio/{identifier}/related/",
								"parts": []any{
									"v1",
									"audio",
									"{identifier}",
									"related",
								},
								"select": map[string]any{
									"$action": "related",
									"exist": []any{
										"identifier",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 1,
							},
							map[string]any{
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"kind": "param",
											"name": "identifier",
											"orig": "identifier",
											"reqd": true,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/v1/audio/{identifier}/waveform/",
								"parts": []any{
									"v1",
									"audio",
									"{identifier}",
									"waveform",
								},
								"select": map[string]any{
									"$action": "waveform",
									"exist": []any{
										"identifier",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 2,
							},
							map[string]any{
								"method": "GET",
								"orig": "/v1/audio/stats/",
								"parts": []any{
									"v1",
									"audio",
									"stats",
								},
								"select": map[string]any{
									"$action": "stat",
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"args": map[string]any{},
								"index$": 3,
							},
						},
						"input": "data",
						"key$": "list",
					},
					"load": map[string]any{
						"name": "load",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"kind": "param",
											"name": "identifier",
											"orig": "identifier",
											"reqd": true,
											"type": "`$STRING`",
											"active": true,
										},
									},
									"query": []any{
										map[string]any{
											"kind": "query",
											"name": "compressed",
											"orig": "compressed",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "full_size",
											"orig": "full_size",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/v1/audio/{identifier}/thumb/",
								"parts": []any{
									"v1",
									"audio",
									"{identifier}",
									"thumb",
								},
								"select": map[string]any{
									"$action": "thumb",
									"exist": []any{
										"compressed",
										"full_size",
										"identifier",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
							map[string]any{
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"kind": "param",
											"name": "identifier",
											"orig": "identifier",
											"reqd": true,
											"type": "`$STRING`",
											"active": true,
										},
									},
									"query": []any{
										map[string]any{
											"kind": "query",
											"name": "compressed",
											"orig": "compressed",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "full_size",
											"orig": "full_size",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/v1/images/{identifier}/thumb/",
								"parts": []any{
									"v1",
									"images",
									"{identifier}",
									"thumb",
								},
								"select": map[string]any{
									"exist": []any{
										"compressed",
										"full_size",
										"identifier",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 1,
							},
							map[string]any{
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"kind": "param",
											"name": "id",
											"orig": "identifier",
											"reqd": true,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/v1/audio/{identifier}/",
								"parts": []any{
									"v1",
									"audio",
									"{id}",
								},
								"rename": map[string]any{
									"param": map[string]any{
										"identifier": "id",
									},
								},
								"select": map[string]any{
									"exist": []any{
										"id",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 2,
							},
						},
						"input": "data",
						"key$": "load",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{
						[]any{
							"audio",
						},
						[]any{
							"image",
						},
					},
				},
			},
			"image": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "attribution",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "author_name",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "author_url",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "category",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 3,
					},
					map[string]any{
						"name": "creator",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 4,
					},
					map[string]any{
						"name": "creator_url",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 5,
					},
					map[string]any{
						"name": "description",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 6,
					},
					map[string]any{
						"name": "detail_url",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 7,
					},
					map[string]any{
						"name": "display_name",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 8,
					},
					map[string]any{
						"name": "fields_matched",
						"req": true,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 9,
					},
					map[string]any{
						"name": "filesize",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 10,
					},
					map[string]any{
						"name": "filetype",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 11,
					},
					map[string]any{
						"name": "foreign_landing_url",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 12,
					},
					map[string]any{
						"name": "height",
						"op": map[string]any{
							"load": map[string]any{
								"req": true,
								"type": "`$INTEGER`",
							},
						},
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 13,
					},
					map[string]any{
						"name": "id",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 14,
					},
					map[string]any{
						"name": "identifier",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 15,
					},
					map[string]any{
						"name": "indexed_on",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 16,
					},
					map[string]any{
						"name": "license",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 17,
					},
					map[string]any{
						"name": "license_url",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 18,
					},
					map[string]any{
						"name": "license_version",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 19,
					},
					map[string]any{
						"name": "logo_url",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 20,
					},
					map[string]any{
						"name": "mature",
						"req": true,
						"type": "`$BOOLEAN`",
						"active": true,
						"index$": 21,
					},
					map[string]any{
						"name": "media_count",
						"req": true,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 22,
					},
					map[string]any{
						"name": "provider",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 23,
					},
					map[string]any{
						"name": "reason",
						"req": true,
						"type": "`$ANY`",
						"active": true,
						"index$": 24,
					},
					map[string]any{
						"name": "related_url",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 25,
					},
					map[string]any{
						"name": "source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 26,
					},
					map[string]any{
						"name": "source_name",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 27,
					},
					map[string]any{
						"name": "source_url",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 28,
					},
					map[string]any{
						"name": "tag",
						"req": true,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 29,
					},
					map[string]any{
						"name": "thumbnail",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 30,
					},
					map[string]any{
						"name": "title",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 31,
					},
					map[string]any{
						"name": "type",
						"req": true,
						"type": "`$ANY`",
						"active": true,
						"index$": 32,
					},
					map[string]any{
						"name": "url",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 33,
					},
					map[string]any{
						"name": "version",
						"req": true,
						"type": "`$ANY`",
						"active": true,
						"index$": 34,
					},
					map[string]any{
						"name": "width",
						"op": map[string]any{
							"load": map[string]any{
								"req": true,
								"type": "`$INTEGER`",
							},
						},
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 35,
					},
				},
				"name": "image",
				"op": map[string]any{
					"create": map[string]any{
						"name": "create",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"kind": "param",
											"name": "identifier",
											"orig": "identifier",
											"reqd": true,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "POST",
								"orig": "/v1/images/{identifier}/report/",
								"parts": []any{
									"v1",
									"images",
									"{identifier}",
									"report",
								},
								"select": map[string]any{
									"$action": "report",
									"exist": []any{
										"identifier",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "create",
					},
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"kind": "query",
											"name": "aspect_ratio",
											"orig": "aspect_ratio",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "category",
											"orig": "category",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "creator",
											"orig": "creator",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "excluded_source",
											"orig": "excluded_source",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "extension",
											"orig": "extension",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": true,
											"kind": "query",
											"name": "filter_dead",
											"orig": "filter_dead",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "license",
											"orig": "license",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "license_type",
											"orig": "license_type",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "mature",
											"orig": "mature",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": 1,
											"kind": "query",
											"name": "page",
											"orig": "page",
											"reqd": false,
											"type": "`$INTEGER`",
											"active": true,
										},
										map[string]any{
											"example": 20,
											"kind": "query",
											"name": "page_size",
											"orig": "page_size",
											"reqd": false,
											"type": "`$INTEGER`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "q",
											"orig": "q",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "size",
											"orig": "size",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "source",
											"orig": "source",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "tag",
											"orig": "tag",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "title",
											"orig": "title",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "unstable_authority",
											"orig": "unstable_authority",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": 1,
											"kind": "query",
											"name": "unstable_authority_boost",
											"orig": "unstable_authority_boost",
											"reqd": false,
											"type": "`$NUMBER`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "unstable_collection",
											"orig": "unstable_collection",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "unstable_include_sensitive_result",
											"orig": "unstable_include_sensitive_result",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": "relevance",
											"kind": "query",
											"name": "unstable_sort_by",
											"orig": "unstable_sort_by",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "desc",
											"kind": "query",
											"name": "unstable_sort_dir",
											"orig": "unstable_sort_dir",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "unstable_tag",
											"orig": "unstable_tag",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/v1/images/",
								"parts": []any{
									"v1",
									"images",
								},
								"select": map[string]any{
									"exist": []any{
										"aspect_ratio",
										"category",
										"creator",
										"excluded_source",
										"extension",
										"filter_dead",
										"license",
										"license_type",
										"mature",
										"page",
										"page_size",
										"q",
										"size",
										"source",
										"tag",
										"title",
										"unstable_authority",
										"unstable_authority_boost",
										"unstable_collection",
										"unstable_include_sensitive_result",
										"unstable_sort_by",
										"unstable_sort_dir",
										"unstable_tag",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
							map[string]any{
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"kind": "param",
											"name": "identifier",
											"orig": "identifier",
											"reqd": true,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/v1/images/{identifier}/related/",
								"parts": []any{
									"v1",
									"images",
									"{identifier}",
									"related",
								},
								"select": map[string]any{
									"$action": "related",
									"exist": []any{
										"identifier",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 1,
							},
							map[string]any{
								"method": "GET",
								"orig": "/v1/images/stats/",
								"parts": []any{
									"v1",
									"images",
									"stats",
								},
								"select": map[string]any{
									"$action": "stat",
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"args": map[string]any{},
								"index$": 2,
							},
						},
						"input": "data",
						"key$": "list",
					},
					"load": map[string]any{
						"name": "load",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"kind": "param",
											"name": "id",
											"orig": "identifier",
											"reqd": true,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/v1/images/{identifier}/",
								"parts": []any{
									"v1",
									"images",
									"{id}",
								},
								"rename": map[string]any{
									"param": map[string]any{
										"identifier": "id",
									},
								},
								"select": map[string]any{
									"exist": []any{
										"id",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
							map[string]any{
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"kind": "query",
											"name": "url",
											"orig": "url",
											"reqd": true,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/v1/images/oembed/",
								"parts": []any{
									"v1",
									"images",
									"oembed",
								},
								"select": map[string]any{
									"$action": "oembed",
									"exist": []any{
										"url",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 1,
							},
						},
						"input": "data",
						"key$": "load",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{
						[]any{
							"image",
						},
					},
				},
			},
			"o_auth2_application": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "description",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "email",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "name",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
				},
				"name": "o_auth2_application",
				"op": map[string]any{
					"create": map[string]any{
						"name": "create",
						"points": []any{
							map[string]any{
								"method": "POST",
								"orig": "/v1/auth_tokens/register/",
								"parts": []any{
									"v1",
									"auth_tokens",
									"register",
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"args": map[string]any{},
								"select": map[string]any{},
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "create",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"o_auth2_key_info": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "rate_limit_model",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "requests_this_minute",
						"req": true,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "requests_today",
						"req": true,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "verified",
						"req": true,
						"type": "`$BOOLEAN`",
						"active": true,
						"index$": 3,
					},
				},
				"name": "o_auth2_key_info",
				"op": map[string]any{
					"load": map[string]any{
						"name": "load",
						"points": []any{
							map[string]any{
								"method": "GET",
								"orig": "/v1/rate_limit/",
								"parts": []any{
									"v1",
									"rate_limit",
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"args": map[string]any{},
								"select": map[string]any{},
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "load",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"o_auth2_token": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "access_token",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "expires_in",
						"req": true,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "scope",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "token_type",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 3,
					},
				},
				"name": "o_auth2_token",
				"op": map[string]any{
					"create": map[string]any{
						"name": "create",
						"points": []any{
							map[string]any{
								"method": "POST",
								"orig": "/v1/auth_tokens/token/",
								"parts": []any{
									"v1",
									"auth_tokens",
									"token",
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"args": map[string]any{},
								"select": map[string]any{},
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "create",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
		},
	}
}

func makeFeature(name string) Feature {
	switch name {
	case "test":
		if NewTestFeatureFunc != nil {
			return NewTestFeatureFunc()
		}
	default:
		if NewBaseFeatureFunc != nil {
			return NewBaseFeatureFunc()
		}
	}
	return nil
}
