# Openverse SDK configuration


def make_config():
    return {
        "main": {
            "name": "Openverse",
        },
        "feature": {
            "test": {
        "options": {
          "active": False,
        },
      },
        },
        "options": {
            "base": "https://api.openverse.org",
            "auth": {
                "prefix": "Bearer",
            },
            "headers": {
        "content-type": "application/json",
      },
            "entity": {
                "audio": {},
                "image": {},
                "o_auth2_application": {},
                "o_auth2_key_info": {},
                "o_auth2_token": {},
            },
        },
        "entity": {
      "audio": {
        "fields": [
          {
            "active": True,
            "name": "alt_file",
            "req": True,
            "type": "`$ARRAY`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "attribution",
            "req": True,
            "type": "`$STRING`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "audio_set",
            "req": True,
            "type": "`$ANY`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "bit_rate",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 3,
          },
          {
            "active": True,
            "name": "category",
            "req": False,
            "type": "`$STRING`",
            "index$": 4,
          },
          {
            "active": True,
            "name": "creator",
            "req": False,
            "type": "`$STRING`",
            "index$": 5,
          },
          {
            "active": True,
            "name": "creator_url",
            "req": False,
            "type": "`$STRING`",
            "index$": 6,
          },
          {
            "active": True,
            "name": "description",
            "req": False,
            "type": "`$STRING`",
            "index$": 7,
          },
          {
            "active": True,
            "name": "detail_url",
            "req": True,
            "type": "`$STRING`",
            "index$": 8,
          },
          {
            "active": True,
            "name": "display_name",
            "req": True,
            "type": "`$STRING`",
            "index$": 9,
          },
          {
            "active": True,
            "name": "duration",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 10,
          },
          {
            "active": True,
            "name": "fields_matched",
            "req": True,
            "type": "`$ARRAY`",
            "index$": 11,
          },
          {
            "active": True,
            "name": "filesize",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 12,
          },
          {
            "active": True,
            "name": "filetype",
            "req": False,
            "type": "`$STRING`",
            "index$": 13,
          },
          {
            "active": True,
            "name": "foreign_landing_url",
            "req": False,
            "type": "`$STRING`",
            "index$": 14,
          },
          {
            "active": True,
            "name": "genre",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 15,
          },
          {
            "active": True,
            "name": "id",
            "req": True,
            "type": "`$STRING`",
            "index$": 16,
          },
          {
            "active": True,
            "name": "identifier",
            "req": True,
            "type": "`$STRING`",
            "index$": 17,
          },
          {
            "active": True,
            "name": "indexed_on",
            "req": True,
            "type": "`$STRING`",
            "index$": 18,
          },
          {
            "active": True,
            "name": "len",
            "req": True,
            "type": "`$INTEGER`",
            "index$": 19,
          },
          {
            "active": True,
            "name": "license",
            "req": True,
            "type": "`$STRING`",
            "index$": 20,
          },
          {
            "active": True,
            "name": "license_url",
            "req": True,
            "type": "`$STRING`",
            "index$": 21,
          },
          {
            "active": True,
            "name": "license_version",
            "req": False,
            "type": "`$STRING`",
            "index$": 22,
          },
          {
            "active": True,
            "name": "logo_url",
            "req": True,
            "type": "`$STRING`",
            "index$": 23,
          },
          {
            "active": True,
            "name": "mature",
            "req": True,
            "type": "`$BOOLEAN`",
            "index$": 24,
          },
          {
            "active": True,
            "name": "media_count",
            "req": True,
            "type": "`$INTEGER`",
            "index$": 25,
          },
          {
            "active": True,
            "name": "point",
            "req": True,
            "type": "`$ARRAY`",
            "index$": 26,
          },
          {
            "active": True,
            "name": "provider",
            "req": False,
            "type": "`$STRING`",
            "index$": 27,
          },
          {
            "active": True,
            "name": "reason",
            "req": True,
            "type": "`$ANY`",
            "index$": 28,
          },
          {
            "active": True,
            "name": "related_url",
            "req": True,
            "type": "`$STRING`",
            "index$": 29,
          },
          {
            "active": True,
            "name": "sample_rate",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 30,
          },
          {
            "active": True,
            "name": "source",
            "req": False,
            "type": "`$STRING`",
            "index$": 31,
          },
          {
            "active": True,
            "name": "source_name",
            "req": True,
            "type": "`$STRING`",
            "index$": 32,
          },
          {
            "active": True,
            "name": "source_url",
            "req": True,
            "type": "`$STRING`",
            "index$": 33,
          },
          {
            "active": True,
            "name": "tag",
            "req": True,
            "type": "`$ARRAY`",
            "index$": 34,
          },
          {
            "active": True,
            "name": "thumbnail",
            "req": True,
            "type": "`$STRING`",
            "index$": 35,
          },
          {
            "active": True,
            "name": "title",
            "req": False,
            "type": "`$STRING`",
            "index$": 36,
          },
          {
            "active": True,
            "name": "url",
            "req": False,
            "type": "`$STRING`",
            "index$": 37,
          },
          {
            "active": True,
            "name": "waveform",
            "req": True,
            "type": "`$STRING`",
            "index$": 38,
          },
        ],
        "name": "audio",
        "op": {
          "create": {
            "input": "data",
            "name": "create",
            "points": [
              {
                "active": True,
                "args": {
                  "params": [
                    {
                      "active": True,
                      "kind": "param",
                      "name": "identifier",
                      "orig": "identifier",
                      "reqd": True,
                      "type": "`$STRING`",
                      "index$": 0,
                    },
                  ],
                },
                "method": "POST",
                "orig": "/v1/audio/{identifier}/report/",
                "parts": [
                  "v1",
                  "audio",
                  "{identifier}",
                  "report",
                ],
                "select": {
                  "$action": "report",
                  "exist": [
                    "identifier",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "create",
          },
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "kind": "query",
                      "name": "category",
                      "orig": "category",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "creator",
                      "orig": "creator",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "excluded_source",
                      "orig": "excluded_source",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "extension",
                      "orig": "extension",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": True,
                      "kind": "query",
                      "name": "filter_dead",
                      "orig": "filter_dead",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "length",
                      "orig": "length",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "license",
                      "orig": "license",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "license_type",
                      "orig": "license_type",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "mature",
                      "orig": "mature",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": 1,
                      "kind": "query",
                      "name": "page",
                      "orig": "page",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "example": 20,
                      "kind": "query",
                      "name": "page_size",
                      "orig": "page_size",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "peak",
                      "orig": "peak",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "q",
                      "orig": "q",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "source",
                      "orig": "source",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "tag",
                      "orig": "tag",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "title",
                      "orig": "title",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "unstable_authority",
                      "orig": "unstable_authority",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": 1,
                      "kind": "query",
                      "name": "unstable_authority_boost",
                      "orig": "unstable_authority_boost",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "unstable_collection",
                      "orig": "unstable_collection",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "unstable_include_sensitive_result",
                      "orig": "unstable_include_sensitive_result",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": "relevance",
                      "kind": "query",
                      "name": "unstable_sort_by",
                      "orig": "unstable_sort_by",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "desc",
                      "kind": "query",
                      "name": "unstable_sort_dir",
                      "orig": "unstable_sort_dir",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "unstable_tag",
                      "orig": "unstable_tag",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/v1/audio/",
                "parts": [
                  "v1",
                  "audio",
                ],
                "select": {
                  "exist": [
                    "category",
                    "creator",
                    "excluded_source",
                    "extension",
                    "filter_dead",
                    "length",
                    "license",
                    "license_type",
                    "mature",
                    "page",
                    "page_size",
                    "peak",
                    "q",
                    "source",
                    "tag",
                    "title",
                    "unstable_authority",
                    "unstable_authority_boost",
                    "unstable_collection",
                    "unstable_include_sensitive_result",
                    "unstable_sort_by",
                    "unstable_sort_dir",
                    "unstable_tag",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
              {
                "active": True,
                "args": {
                  "params": [
                    {
                      "active": True,
                      "kind": "param",
                      "name": "identifier",
                      "orig": "identifier",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/v1/audio/{identifier}/related/",
                "parts": [
                  "v1",
                  "audio",
                  "{identifier}",
                  "related",
                ],
                "select": {
                  "$action": "related",
                  "exist": [
                    "identifier",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 1,
              },
              {
                "active": True,
                "args": {
                  "params": [
                    {
                      "active": True,
                      "kind": "param",
                      "name": "identifier",
                      "orig": "identifier",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/v1/audio/{identifier}/waveform/",
                "parts": [
                  "v1",
                  "audio",
                  "{identifier}",
                  "waveform",
                ],
                "select": {
                  "$action": "waveform",
                  "exist": [
                    "identifier",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 2,
              },
              {
                "active": True,
                "args": {},
                "method": "GET",
                "orig": "/v1/audio/stats/",
                "parts": [
                  "v1",
                  "audio",
                  "stats",
                ],
                "select": {
                  "$action": "stat",
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 3,
              },
            ],
            "key$": "list",
          },
          "load": {
            "input": "data",
            "name": "load",
            "points": [
              {
                "active": True,
                "args": {
                  "params": [
                    {
                      "active": True,
                      "kind": "param",
                      "name": "identifier",
                      "orig": "identifier",
                      "reqd": True,
                      "type": "`$STRING`",
                      "index$": 0,
                    },
                  ],
                  "query": [
                    {
                      "active": True,
                      "kind": "query",
                      "name": "compressed",
                      "orig": "compressed",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "full_size",
                      "orig": "full_size",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/v1/audio/{identifier}/thumb/",
                "parts": [
                  "v1",
                  "audio",
                  "{identifier}",
                  "thumb",
                ],
                "select": {
                  "$action": "thumb",
                  "exist": [
                    "compressed",
                    "full_size",
                    "identifier",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
              {
                "active": True,
                "args": {
                  "params": [
                    {
                      "active": True,
                      "kind": "param",
                      "name": "identifier",
                      "orig": "identifier",
                      "reqd": True,
                      "type": "`$STRING`",
                      "index$": 0,
                    },
                  ],
                  "query": [
                    {
                      "active": True,
                      "kind": "query",
                      "name": "compressed",
                      "orig": "compressed",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "full_size",
                      "orig": "full_size",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/v1/images/{identifier}/thumb/",
                "parts": [
                  "v1",
                  "images",
                  "{identifier}",
                  "thumb",
                ],
                "select": {
                  "exist": [
                    "compressed",
                    "full_size",
                    "identifier",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 1,
              },
              {
                "active": True,
                "args": {
                  "params": [
                    {
                      "active": True,
                      "kind": "param",
                      "name": "id",
                      "orig": "identifier",
                      "reqd": True,
                      "type": "`$STRING`",
                      "index$": 0,
                    },
                  ],
                },
                "method": "GET",
                "orig": "/v1/audio/{identifier}/",
                "parts": [
                  "v1",
                  "audio",
                  "{id}",
                ],
                "rename": {
                  "param": {
                    "identifier": "id",
                  },
                },
                "select": {
                  "exist": [
                    "id",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 2,
              },
            ],
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [
            [
              "audio",
            ],
            [
              "image",
            ],
          ],
        },
      },
      "image": {
        "fields": [
          {
            "active": True,
            "name": "attribution",
            "req": True,
            "type": "`$STRING`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "author_name",
            "req": True,
            "type": "`$STRING`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "author_url",
            "req": True,
            "type": "`$STRING`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "category",
            "req": False,
            "type": "`$STRING`",
            "index$": 3,
          },
          {
            "active": True,
            "name": "creator",
            "req": False,
            "type": "`$STRING`",
            "index$": 4,
          },
          {
            "active": True,
            "name": "creator_url",
            "req": False,
            "type": "`$STRING`",
            "index$": 5,
          },
          {
            "active": True,
            "name": "description",
            "req": False,
            "type": "`$STRING`",
            "index$": 6,
          },
          {
            "active": True,
            "name": "detail_url",
            "req": True,
            "type": "`$STRING`",
            "index$": 7,
          },
          {
            "active": True,
            "name": "display_name",
            "req": True,
            "type": "`$STRING`",
            "index$": 8,
          },
          {
            "active": True,
            "name": "fields_matched",
            "req": True,
            "type": "`$ARRAY`",
            "index$": 9,
          },
          {
            "active": True,
            "name": "filesize",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 10,
          },
          {
            "active": True,
            "name": "filetype",
            "req": False,
            "type": "`$STRING`",
            "index$": 11,
          },
          {
            "active": True,
            "name": "foreign_landing_url",
            "req": False,
            "type": "`$STRING`",
            "index$": 12,
          },
          {
            "active": True,
            "name": "height",
            "op": {
              "load": {
                "req": True,
                "type": "`$INTEGER`",
              },
            },
            "req": False,
            "type": "`$INTEGER`",
            "index$": 13,
          },
          {
            "active": True,
            "name": "id",
            "req": True,
            "type": "`$STRING`",
            "index$": 14,
          },
          {
            "active": True,
            "name": "identifier",
            "req": True,
            "type": "`$STRING`",
            "index$": 15,
          },
          {
            "active": True,
            "name": "indexed_on",
            "req": True,
            "type": "`$STRING`",
            "index$": 16,
          },
          {
            "active": True,
            "name": "license",
            "req": True,
            "type": "`$STRING`",
            "index$": 17,
          },
          {
            "active": True,
            "name": "license_url",
            "req": True,
            "type": "`$STRING`",
            "index$": 18,
          },
          {
            "active": True,
            "name": "license_version",
            "req": False,
            "type": "`$STRING`",
            "index$": 19,
          },
          {
            "active": True,
            "name": "logo_url",
            "req": True,
            "type": "`$STRING`",
            "index$": 20,
          },
          {
            "active": True,
            "name": "mature",
            "req": True,
            "type": "`$BOOLEAN`",
            "index$": 21,
          },
          {
            "active": True,
            "name": "media_count",
            "req": True,
            "type": "`$INTEGER`",
            "index$": 22,
          },
          {
            "active": True,
            "name": "provider",
            "req": False,
            "type": "`$STRING`",
            "index$": 23,
          },
          {
            "active": True,
            "name": "reason",
            "req": True,
            "type": "`$ANY`",
            "index$": 24,
          },
          {
            "active": True,
            "name": "related_url",
            "req": True,
            "type": "`$STRING`",
            "index$": 25,
          },
          {
            "active": True,
            "name": "source",
            "req": False,
            "type": "`$STRING`",
            "index$": 26,
          },
          {
            "active": True,
            "name": "source_name",
            "req": True,
            "type": "`$STRING`",
            "index$": 27,
          },
          {
            "active": True,
            "name": "source_url",
            "req": True,
            "type": "`$STRING`",
            "index$": 28,
          },
          {
            "active": True,
            "name": "tag",
            "req": True,
            "type": "`$ARRAY`",
            "index$": 29,
          },
          {
            "active": True,
            "name": "thumbnail",
            "req": True,
            "type": "`$STRING`",
            "index$": 30,
          },
          {
            "active": True,
            "name": "title",
            "req": False,
            "type": "`$STRING`",
            "index$": 31,
          },
          {
            "active": True,
            "name": "type",
            "req": True,
            "type": "`$ANY`",
            "index$": 32,
          },
          {
            "active": True,
            "name": "url",
            "req": False,
            "type": "`$STRING`",
            "index$": 33,
          },
          {
            "active": True,
            "name": "version",
            "req": True,
            "type": "`$ANY`",
            "index$": 34,
          },
          {
            "active": True,
            "name": "width",
            "op": {
              "load": {
                "req": True,
                "type": "`$INTEGER`",
              },
            },
            "req": False,
            "type": "`$INTEGER`",
            "index$": 35,
          },
        ],
        "name": "image",
        "op": {
          "create": {
            "input": "data",
            "name": "create",
            "points": [
              {
                "active": True,
                "args": {
                  "params": [
                    {
                      "active": True,
                      "kind": "param",
                      "name": "identifier",
                      "orig": "identifier",
                      "reqd": True,
                      "type": "`$STRING`",
                      "index$": 0,
                    },
                  ],
                },
                "method": "POST",
                "orig": "/v1/images/{identifier}/report/",
                "parts": [
                  "v1",
                  "images",
                  "{identifier}",
                  "report",
                ],
                "select": {
                  "$action": "report",
                  "exist": [
                    "identifier",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "create",
          },
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "kind": "query",
                      "name": "aspect_ratio",
                      "orig": "aspect_ratio",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "category",
                      "orig": "category",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "creator",
                      "orig": "creator",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "excluded_source",
                      "orig": "excluded_source",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "extension",
                      "orig": "extension",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": True,
                      "kind": "query",
                      "name": "filter_dead",
                      "orig": "filter_dead",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "license",
                      "orig": "license",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "license_type",
                      "orig": "license_type",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "mature",
                      "orig": "mature",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": 1,
                      "kind": "query",
                      "name": "page",
                      "orig": "page",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "example": 20,
                      "kind": "query",
                      "name": "page_size",
                      "orig": "page_size",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "q",
                      "orig": "q",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "size",
                      "orig": "size",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "source",
                      "orig": "source",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "tag",
                      "orig": "tag",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "title",
                      "orig": "title",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "unstable_authority",
                      "orig": "unstable_authority",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": 1,
                      "kind": "query",
                      "name": "unstable_authority_boost",
                      "orig": "unstable_authority_boost",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "unstable_collection",
                      "orig": "unstable_collection",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "unstable_include_sensitive_result",
                      "orig": "unstable_include_sensitive_result",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": "relevance",
                      "kind": "query",
                      "name": "unstable_sort_by",
                      "orig": "unstable_sort_by",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "desc",
                      "kind": "query",
                      "name": "unstable_sort_dir",
                      "orig": "unstable_sort_dir",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "unstable_tag",
                      "orig": "unstable_tag",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/v1/images/",
                "parts": [
                  "v1",
                  "images",
                ],
                "select": {
                  "exist": [
                    "aspect_ratio",
                    "category",
                    "creator",
                    "excluded_source",
                    "extension",
                    "filter_dead",
                    "license",
                    "license_type",
                    "mature",
                    "page",
                    "page_size",
                    "q",
                    "size",
                    "source",
                    "tag",
                    "title",
                    "unstable_authority",
                    "unstable_authority_boost",
                    "unstable_collection",
                    "unstable_include_sensitive_result",
                    "unstable_sort_by",
                    "unstable_sort_dir",
                    "unstable_tag",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
              {
                "active": True,
                "args": {
                  "params": [
                    {
                      "active": True,
                      "kind": "param",
                      "name": "identifier",
                      "orig": "identifier",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/v1/images/{identifier}/related/",
                "parts": [
                  "v1",
                  "images",
                  "{identifier}",
                  "related",
                ],
                "select": {
                  "$action": "related",
                  "exist": [
                    "identifier",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 1,
              },
              {
                "active": True,
                "args": {},
                "method": "GET",
                "orig": "/v1/images/stats/",
                "parts": [
                  "v1",
                  "images",
                  "stats",
                ],
                "select": {
                  "$action": "stat",
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 2,
              },
            ],
            "key$": "list",
          },
          "load": {
            "input": "data",
            "name": "load",
            "points": [
              {
                "active": True,
                "args": {
                  "params": [
                    {
                      "active": True,
                      "kind": "param",
                      "name": "id",
                      "orig": "identifier",
                      "reqd": True,
                      "type": "`$STRING`",
                      "index$": 0,
                    },
                  ],
                },
                "method": "GET",
                "orig": "/v1/images/{identifier}/",
                "parts": [
                  "v1",
                  "images",
                  "{id}",
                ],
                "rename": {
                  "param": {
                    "identifier": "id",
                  },
                },
                "select": {
                  "exist": [
                    "id",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "kind": "query",
                      "name": "url",
                      "orig": "url",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/v1/images/oembed/",
                "parts": [
                  "v1",
                  "images",
                  "oembed",
                ],
                "select": {
                  "$action": "oembed",
                  "exist": [
                    "url",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 1,
              },
            ],
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [
            [
              "image",
            ],
          ],
        },
      },
      "o_auth2_application": {
        "fields": [
          {
            "active": True,
            "name": "description",
            "req": True,
            "type": "`$STRING`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "email",
            "req": True,
            "type": "`$STRING`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "name",
            "req": True,
            "type": "`$STRING`",
            "index$": 2,
          },
        ],
        "name": "o_auth2_application",
        "op": {
          "create": {
            "input": "data",
            "name": "create",
            "points": [
              {
                "active": True,
                "args": {},
                "method": "POST",
                "orig": "/v1/auth_tokens/register/",
                "parts": [
                  "v1",
                  "auth_tokens",
                  "register",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "create",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "o_auth2_key_info": {
        "fields": [
          {
            "active": True,
            "name": "rate_limit_model",
            "req": True,
            "type": "`$STRING`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "requests_this_minute",
            "req": True,
            "type": "`$INTEGER`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "requests_today",
            "req": True,
            "type": "`$INTEGER`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "verified",
            "req": True,
            "type": "`$BOOLEAN`",
            "index$": 3,
          },
        ],
        "name": "o_auth2_key_info",
        "op": {
          "load": {
            "input": "data",
            "name": "load",
            "points": [
              {
                "active": True,
                "args": {},
                "method": "GET",
                "orig": "/v1/rate_limit/",
                "parts": [
                  "v1",
                  "rate_limit",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "o_auth2_token": {
        "fields": [
          {
            "active": True,
            "name": "access_token",
            "req": True,
            "type": "`$STRING`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "expires_in",
            "req": True,
            "type": "`$INTEGER`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "scope",
            "req": True,
            "type": "`$STRING`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "token_type",
            "req": True,
            "type": "`$STRING`",
            "index$": 3,
          },
        ],
        "name": "o_auth2_token",
        "op": {
          "create": {
            "input": "data",
            "name": "create",
            "points": [
              {
                "active": True,
                "args": {},
                "method": "POST",
                "orig": "/v1/auth_tokens/token/",
                "parts": [
                  "v1",
                  "auth_tokens",
                  "token",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "create",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
    },
    }
